lab_1/urls.py
from django.urls import path
from .views import friend_list, index

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    # nama url buat garing
    # isi url -> friend_list
    # name -> buat nama aja
    path('friends', friend_list, name='friend'),
]

lab_2/urls.py
from django.urls import path
from .views import index, json, xml

urlpatterns = [
    path('', index, name='index'),    
    path('xml', xml, name='xml'),    
    path('json', json, name='json'),    
]

lab_3/urls.py
from django.urls import path
from .views import add_friend, index

urlpatterns = [
    path('', index, name='index'),    
    path('add', add_friend, name='add_friend'),    
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

urlpatterns = [
    path('', index, name='index'),  
    path('add-note', add_note, name='add_note'), 
    path('note-list', note_list, name='note_list'),
]

praktikum/urls.py
from django.urls import path, re_path
from django.contrib import admin
from django.urls.conf import include
import lab_1.urls as lab_1
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),

    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model

    npm = models.CharField(max_length=10)

    dob = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    dari = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    message = models.CharField(max_length=100)

lab_3/models.py
from django.db import models
from django.forms.models import ModelForm

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model

    npm = models.CharField(max_length=10)

    dob = models.DateField()

lab_4/models.py
from django.db import models

# Create your models here.
# class Note(models.Model):
#     to = models.CharField(max_length=30)
#     dari = models.CharField(max_length=30)
#     title = models.CharField(max_length=30)
#     message = models.TextField()

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django import forms
from .models import Friend

class DateInput(forms.DateInput):
    input_type = 'date'

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"
        widgets = {'dob' : DateInput()}

lab_4/forms.py
from django import forms
from lab_2.models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = "__all__"

lab_1/views.py
from lab_1.models import Friend
from django.shortcuts import render
from datetime import datetime, date

mhs_name = 'Shabrina Salsabila Kurniawan'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2003, 5, 18)  # TODO Implement this, format (Year, Month, Date)
npm = 2006464745  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from lab_2.models import Note
from django.shortcuts import render
from django.http.response import HttpResponse
from django.core import serializers

# Create your views here.

def index(request):
    note = Note.objects.all()
    response = {'note': note}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.http import response
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import Friend
from .forms import FriendForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    response = {}
    dari = FriendForm(request.POST or None)
    if(dari.is_valid() and request.method == 'POST'):
        dari.save()
        return HttpResponseRedirect('/lab-3')
    response['dari'] = dari
    return render(request, 'lab3_form.html', response)

lab_4/views.py
from django.shortcuts import render
from lab_2.models import Note
from django.http.response import HttpResponseRedirect
from .forms import NoteForm
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/admin/login/')
def index(request):
    note = Note.objects.all()
    response = {'note': note}
    return render(request, 'lab4_index.html', response)
    
@login_required(login_url='/admin/login/')
def add_note(request):
    response = {}
    note = NoteForm(request.POST or None)
    if(note.is_valid() and request.method == 'POST'):
        note.save()
        return HttpResponseRedirect('/lab-4')
    response['note'] = note
    return render(request, 'lab4_form.html', response)

@login_required(login_url='/admin/login/')
def note_list(request):
    note = Note.objects.all()
    response = {'note': note}
    return render(request, 'lab4_note_list.html', response)

lab_5/views.py
from django.shortcuts import render

# Create your views here.

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      <!-- EXAMPLE SECTION -->
      {% for var in friends %}
      <tr>
        <td>{{var.name}}</td>
        <td>{{var.npm}}</td>
        <td>{{var.dob}}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% for var in note%}
      <tr>
        <td>{{var.to}}</td>
        <td>{{var.dari}}</td>
        <td>{{var.title}}</td>
        <td>{{var.message}}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <h1>Friend List</h1>
    <table>
      <form action="" method="POST">
          {% csrf_token %}

          {{dari.as_p}}

          <input type="submit" value="Submit">
      </form>
    </table>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      <!-- EXAMPLE SECTION -->
      {% for var in friends %}
      <tr>
        <td>{{var.name}}</td>
        <td>{{var.npm}}</td>
        <td>{{var.dob}}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <title>Note Form</title>
    <style>
      body{
        margin: 0;
        padding: 0;
        font-family: montserrat;
        background: linear-gradient(120deg, #00c3ff, #ffff1c);
        height: 100vh;
        overflow: hidden;
      }
      .center{
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          width: 600px;
          background: white;
          border-radius: 10px;
          box-shadow: 10px 10px 15px rgba(0,0,0,0.05);
      }
      .center h1{
          text-align: center;
          padding: 20px 0;
          border-bottom: 1px solid silver;
      }
      .center form{
          padding: 0 40px;
          box-sizing: border-box;
      }
      form .to_field{
          position: relative;
          border-bottom: 2px solid #adadad;
          margin: 30px 0;
      }
      .to_field input{
          width: 502px;
          padding: 0 5px;
          height: 40px;
          font-size: 16px;
          font-family: montserrat;
          border: none;
          background: none;
          outline: none;
      }
      .to_field label{
          position: absolute;
          top: 50%;
          left: 5px;
          color: #adadad;
          transform: translateY(-50%);
          font-size: 16px;
          pointer-events: none;
          transition: .5s;
      }
      .to_field span::before {
          content: '';
          position: absolute;
          top: 10px;
          left: 0;
          width: 0%;
          height: 2px;
          background: #00c3ff;
          margin: 30px 0;
          transition: .5s;
      }
      .to_field input:focus ~ label,
      .to_field input:valid ~ label{
          top: -5px;
          color: #00c3ff;
      }
      .to_field input:focus ~ span::before,
      .to_field input:valid ~ span::before{
          width: 100%;
      }

      input[type="submit"]{
          width: 100%;
          height: 50px;
          border: 1px solid;
          background:#1cafdb;
          border-radius: 25px;
          font-size: 18px;
          color: #e9f4fb;
          font-weight: 700;
          cursor: pointer;
          outline: none;
          margin: 30px 0;
      }

      ul{
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background: #F9F871;
      }

      li{
        float: right;
      }

      li a{
        display: block;
        padding: 14px 16px;
        color: black;
        text-decoration: none;
        font-family:  montserrat;
      }

    </style>
  </head>
  <body>

    <ul>
      <li><a href="/lab-4/">List</a></li>
      <li><a href="add-note">Send</a></li>
      <li><a href="note-list">Card</a></li>
    </ul>

    <div class="center">
      <h1>Send Message to Someone</h1>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="to_field">
          <input id="id_to" type="text" name="to" required>
          <span></span>
          <label for="id_to">To</label><br>
        </div>

        <div class="to_field">
          <input id="id_dari" type="text" name="dari" required>
          <span></span>
          <label for="id_dari">From</label><br>
        </div>

        <div class="to_field">
          <input id="id_title" type="text" name="title" required>
          <span></span>
          <label for="id_title">Title</label><br>
        </div>

        <div class="to_field">
          <input id="id_message" type="text" name="message" required>
          <span></span>
          <label for="id_message">Message</label><br>
        </div>

        <input type="submit" value="Send">
      </form>
    </div>
  </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
    <style>
      body{
        margin: 0;
        padding: 0;
        background: linear-gradient(120deg, #00c3ff, #ffff1c);
        height: 100vh;
        overflow: hidden;
      }

      table{
          position: absolute;
          z-index: 2;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
          width: 60%;
          border: collapse;
          border-spacing:0 ;
          border-radius: 12px 12px 0 0;
          overflow: hidden;
          box-shadow: 0 1px 10px rgba(250, 250, 250, 1);
          background: #fafafa;
          text-align: center;
      }

      th,td{
          padding: 10px 15px;
      }

      th{
          font-family: montserrat;
          background: #F9F871;
          text-transform: uppercase;
      }

      tr{
          font-family: sans-serif;
      }

      tr:nth-child(even){
          background-color: #eeeeee;
      }

      ul{
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background: #F9F871;
      }

      li{
        float: right;
      }

      li a{
        display: block;
        padding: 14px 16px;
        color: black;
        text-decoration: none;
        font-family:  montserrat;
      }

    </style>
  </head>
  <body>
      <ul>
        <li><a href="/lab-4/">List</a></li>
        <li><a href="/lab-4/add-note">Send</a></li>
        <li><a href="/lab-4/note-list">Card</a></li>
      </ul>
    
    <table>
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% if note %}
        {% for var in note %}
        <tr>
          <td>{{var.to}}</td>
          <td>{{var.dari}}</td>
          <td>{{var.title}}</td>
          <td>{{var.message}}</td>
        </tr>
        {% endfor %}
      {% endif %}
    </table>
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Note List</title>
        <style>
            body{
                padding: 0;
                margin: 0;
            }
            .isi {
                margin: 0;
                padding: 0;
                font-family: montserrat;
                min-height: 100vh;
                display: flex;
                justify-content: flex;
                background: linear-gradient(120deg, #00c3ff, #ffff1c);
            }

            .card{
                background-color: transparent;
                width:500%;
                height: 300px;
                perspective: 1000px;
                display: flex;
                justify-content: flex;
                align-items: center;
                margin-left: 30px;
                margin-right: 40px;
                margin-top: 200px;
                justify-self: auto;
                
            }

            .inner{
                background-color: #2980b9;
                margin: 20px;
                padding: 25px;
                justify-self: auto;
                position: relative;
                width: 300px;
                height: 100%;
                text-align: center;
                transition: transform 0.6s;
                transform-style: preserve-3d;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

            .card:hover .inner{
                transform: rotateY(180deg);
            }

            .front, .back{
                position: absolute;
                width: 100%;
                height: 100%;
                -webkit-backface-visibility: hidden;
                backface-visibility: hidden;
            }

            .front{
                background-color: #F9F871;
                text-align: center;
                color: black;
            }

            .back{
                background-color:#F9F871;
                color: black;
                transform: rotateY(180deg);
                
            }

            ul{
                padding: 0;
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background: #F9F871;
                width: auto;
            }

            li{
                float: right;
            }

            li a{
                display: block;
                padding: 14px 16px;
                color: black;
                text-decoration: none;
                font-family:  montserrat;
            }
        </style>
    </head>

    <body>
        
        <ul>
            <li><a href="/lab-4/">List</a></li>
            <li><a href="add-note">Send</a></li>
            <li><a href="note-list">Card</a></li>
        </ul>
        <div class="isi">
    
            {%for var in note%}
            <div class="card">
                <div class="inner">
                    <div class="front">
                        <h1>{{var.title}}</h1>
                    </div>
    
                    <div class="back">
                        <h3>To {{var.to}},</h3>
                        <h3>From {{var.dari}}</h3>
                        <p>{{var.message}}</p>
                    </div>
                </div>
            </div>
            {%endfor%} 
        </div>
    </body>
</html>